on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
# tests and coverage
name: run tests
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17.x
      - name: Checkout code
        uses: actions/checkout@v2
      - name: set path
        run: |
          export PATH=${GOROOT}/bin:$PATH
      - name: deps
        run: go get -t unziploc
      - name: Run linters
        uses: golangci/golangci-lint-action@v2
        with:
          version: v1.29
          skip-go-installation: true
          skip-pkg-cache: true

  test:
    strategy:
      matrix:
        go-version: [1.17.x]
        platform: [ubuntu-latest]
    runs-on: ${{ matrix.platform }}
    container:
      image: golang:latest
      options: --user root
    steps:
      - name: Install Go
        if: success()
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go-version }}
      - name: Checkout code
        uses: actions/checkout@v2
      - name: set path
        run: export PATH=${GOROOT}/bin:$PATH
      - name: deps
        run: go get -t unziploc
      - name: Run tests
        run: go test -v -covermode=count


  coverage:
    runs-on: ubuntu-latest
    container:
      image: golang:latest
      options: --user root
    steps:
      - name: Install Go
        if: success()
        uses: actions/setup-go@v2
        with:
          go-version: 1.17.x
      - name: Checkout code
        uses: actions/checkout@v2
      - name: set path
        run: export PATH=${GOROOT}/bin:$PATH
      - name: deps
        run: go get -t unziploc
      - name: Calc coverage
        run: go test -v -covermode=count -coverprofile=coverage.out
      - name: Convert coverage.out to coverage.lcov
        uses: jandelgado/gcov2lcov-action@v1.0.6
      - name: Coveralls
        uses: coverallsapp/github-action@v1.1.2
        with:
          github-token: ${{ secrets.github_token }}
          path-to-lcov: coverage.lcov
  docker:
    runs-on: ubuntu-latest
    if: success()
    environment: default
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1

        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: blackbird7181/unziploc:latest